export const interventionsTypes = [
  { label: "Adjust Gantry Brakes", value: "ADJUST_GANTRY_BRAKES" },
  { label: "Adjust Service Brakes", value: "ADJUST_SERVICE_BRAKES" },
  { label: "Adjust Trim Support Sensor", value: "ADJUST_TRIM_SUPPORT_SENSOR" },
  { label: "Adjust Trolley Brakes", value: "ADJUST_TROLLEY_BRAKES" },
  { label: "Adjust Trolley Chain", value: "ADJUST_TROLLEY_CHAIN" },
  { label: "Change 1 Battery", value: "CHANGE_1_BATTERY" },
  { label: "Change 4 Batteries", value: "CHANGE_4_BATTERIES" },
  {
    label: "Change Anti Collision System",
    value: "CHANGE_ANTI_COLLISION_SYSTEM",
  },
  { label: "Change CUVC Gantry Card", value: "CHANGE_CUVC_GANTRY_CARD" },
  { label: "Change Generator", value: "CHANGE_GENERATOR" },
  { label: "Change Hydraulic Oil", value: "CHANGE_HYDRAULIC_OIL" },
  { label: "Change Motor Pipe", value: "CHANGE_MOTOR_PIPE" },
  { label: "Change PLC Battery", value: "CHANGE_PLC_BATTERY" },
  {
    label: "Change Touch Panel Driver Cabin",
    value: "CHANGE_TOUCH_PANEL_DRIVER_CABIN",
  },
  { label: "Change Trolley Encoder", value: "CHANGE_TROLLEY_ENCODER" },
  { label: "Change Variator", value: "CHANGE_VARIATOR" },
  {
    label: "Change Water Inlet Connection",
    value: "CHANGE_WATER_INLET_CONNECTION",
  },
  {
    label: "Check and Change Reducer Shaft",
    value: "CHECK_AND_CHANGE_REDUCER_SHAFT",
  },
  {
    label: "Check and Fix Crane Problem",
    value: "CHECK_AND_FIX_CRANE_PROBLEM",
  },
  {
    label: "Check and Fix Engine Startup Problem",
    value: "CHECK_AND_FIX_ENGINE_STARTUP_PROBLEM",
  },
  {
    label: "Check and Fix Gate Lock Problem",
    value: "CHECK_AND_FIX_GATE_LOCK_PROBLEM",
  },
  { label: "Check and Fix Trolley P6", value: "CHECK_AND_FIX_TROLLEY_P6" },
  { label: "Check and Fix Twin", value: "CHECK_AND_FIX_TWIN" },
  {
    label: "Check and Repair 400V Problem",
    value: "CHECK_AND_REPAIR_400V_PROBLEM",
  },
  {
    label: "Check and Repair Emergency Brakes Problem",
    value: "CHECK_AND_REPAIR_EMERGENCY_BRAKES_PROBLEM",
  },
  {
    label: "Check and Repair Gantry Problem",
    value: "CHECK_AND_REPAIR_GANTRY_PROBLEM",
  },
  {
    label: "Check and Repair Trim Problem",
    value: "CHECK_AND_REPAIR_TRIM_PROBLEM",
  },
  {
    label: "Check and Repair Trolley Problem",
    value: "CHECK_AND_REPAIR_TROLLEY_PROBLEM",
  },
  { label: "Check Gantry Problem", value: "CHECK_GANTRY_PROBLEM" },
  { label: "Check Hoist Problem", value: "CHECK_HOIST_PROBLEM" },
  { label: "Check Spreader Cable Reel", value: "CHECK_SPREADER_CABLE_REEL" },
  { label: "Check Steering Problem", value: "CHECK_STEERING_PROBLEM" },
  { label: "Check Trim Problem", value: "CHECK_TRIM_PROBLEM" },
  {
    label: "Check Water Leaking Problem",
    value: "CHECK_WATER_LEAKING_PROBLEM",
  },
  { label: "CM", value: "CM" },
  {
    label: "Dismount Gantry Reducer Corner 4",
    value: "DISMOUNT_GANTRY_REDUCER_CORNER_4",
  },
  { label: "Dismount Trolley Wheel", value: "DISMOUNT_TROLLEY_WHEEL" },
  { label: "Dismount Water Pump", value: "DISMOUNT_WATER_PUMP" },
  { label: "General Control", value: "GENERAL_CONTROL" },
  { label: "General Testing", value: "GENERAL_TESTING" },
  { label: "Inflate the Tires", value: "INFLATE_THE_TIRES" },
  {
    label: "Install Hoist Gantry Joystick",
    value: "INSTALL_HOIST_GANTRY_JOYSTICK",
  },
  { label: "Install the Missing Parts", value: "INSTALL_THE_MISSING_PARTS" },
  { label: "Install the Pin", value: "INSTALL_THE_PIN" },
  { label: "PM 1000 Hoist", value: "PM_1000_HOIST" },
  { label: "PM 1000 Spreader", value: "PM_1000_SPREADER" },
  { label: "PM 2000 Trolley", value: "PM_2000_TROLLEY" },
  { label: "PM 3000 Gantry", value: "PM_3000_GANTRY" },
  { label: "PM 500", value: "PM_500" },
  { label: "PM 5000", value: "PM_5000" },
  { label: "Replace Trolley Wheels", value: "REPLACE_TROLLEY_WHEELS" },
  { label: "Uninstall Pin", value: "UNINSTALL_PIN" },
];
